<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>WAMFF</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <Nullable>enable</Nullable>
    <LangVersion>Preview</LangVersion>
    <EnableMsixTooling>true</EnableMsixTooling>
    <EnablePreviewMsixTooling>true</EnablePreviewMsixTooling>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <ProjectCapability Include="Msix" />
  </ItemGroup>
  
  <ItemGroup>
    <Content Include="Assets\StoreLogo.png" />
    <Manifest Include="$(ApplicationManifest)" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="CommunityToolkit.WinUI.Helpers" Version="8.2.250402" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250310001" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.3" />
    <ProjectReference Include="..\WAMFF.Core\WAMFF.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Components\TagDisplayCollection.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Components\CategoryDisplay.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Components\FileDisplayColletion.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Components\TitleBar.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Components\CategoryDisplayCollection.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Components\FileDisplay.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <!--
    Defining the "HasPackageAndPublishMenuAddedByProject" property here allows the Solution
    Explorer "Package and Publish" context menu entry to be enabled for this project even if
    the Windows App SDK Nuget package has not yet been restored.
  -->
  <PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
    <HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
  </PropertyGroup>
  <!-- Publish Properties -->
  <PropertyGroup>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
    <SupportedOSPlatformVersion>10.0.26100.0</SupportedOSPlatformVersion>
    <ApplicationIcon>Assets\StoreLogo.ico</ApplicationIcon>
  </PropertyGroup>
</Project>